name: Coverage

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/cache@v5
        name: Cache NuGet
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.x
            10.x

      - name: Restore
        run: dotnet restore

      - name: Test (Unit) with Coverage
        run: >
          dotnet test test/ClickHouse.Tests/ClickHouse.Tests.csproj
          --configuration Release
          --verbosity normal
          --logger GitHubActions
          /clp:ErrorsOnly
          /p:CollectCoverage=true
          /p:CoverletOutputFormat=opencover
          /p:SkipAutoProps=true
          /p:Include="[ClickHouse.SemanticKernel]*"

      - name: Test (Conformance) with Coverage
        run: >
          dotnet test test/ClickHouse.ConformanceTests/ClickHouse.ConformanceTests.csproj
          --configuration Release
          --verbosity normal
          --logger GitHubActions
          /clp:ErrorsOnly
          /p:CollectCoverage=true
          /p:CoverletOutputFormat=opencover
          /p:SkipAutoProps=true
          /p:Include="[ClickHouse.SemanticKernel]*"

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          disable_search: true
          verbose: true
          files: ./test/ClickHouse.Tests/coverage.opencover.xml,./test/ClickHouse.ConformanceTests/coverage.opencover.xml
